"""create chat model

Revision ID: d52b21f0baa0
Revises: 05ddf9874b52
Create Date: 2026-08-09 15:35:35.360391

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d52b21f0baa0"
down_revision: Union[str, Sequence[str], None] = "05ddf9874b52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_chats_created_at"), "chats", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_chats_owner_id"), "chats", ["owner_id"], unique=False
    )
    op.add_column(
        "chat_messages", sa.Column("chat_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(None, "chat_messages", "chats", ["chat_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_messages", type_="foreignkey")
    op.drop_column("chat_messages", "chat_id")
    op.drop_index(op.f("ix_chats_owner_id"), table_name="chats")
    op.drop_index(op.f("ix_chats_created_at"), table_name="chats")
    op.drop_table("chats")
    # ### end Alembic commands ###
